CREATE TABLE IF NOT EXISTS Genre (
	GenreID SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Artist (
	ArtistID SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	GenreID INT REFERENCES Genre(GenreID)
);

CREATE TABLE IF NOT EXISTS Album (
	AlbumID SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL UNIQUE,
	year INT NOT NULL,
	ArtistID INT NOT NULL REFERENCES Artist(ArtistID)
);

CREATE TABLE IF NOT EXISTS Track (
	TrackID SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	lenght INT,
	AlbumID INT NOT NULL REFERENCES Album(AlbumID)
);

CREATE TABLE IF NOT EXISTS Collection (
	CollectionID SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	year INT
);
 
CREATE TABLE IF NOT EXISTS CollectionTrack (
	CollectionID SERIAL PRIMARY KEY,
	TrackID INT REFERENCES Track(TrackID),
	PRIMARY KEY (CollectionID, TrackID)
);